services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ripley_data:/app/ripley_output
    depends_on:
      - frontend
    deploy:
      resources:
        limits:
          memory: 8G
    
    
  

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
volumes:
  ripley_data: